<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE musicos [
  <!ELEMENT musicos (musico*)><!-- ok-->
  <!ELEMENT musico ((nombre | apodo), fechaNacimiento)><!-- <musico> debe estar formado por un <nombre> o un <apodo>, y una <fechaNacimiento>-->
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apodo (#PCDATA)>
  <!ELEMENT fechaNacimiento (#PCDATA)>
]>

<musicos>
  <musico>
    <nombre>Antonio Vivaldi (El cura pelirrojillo)</nombre>
    <!--<apodo>El cura pelirrojillo</apodo>-->
    <fechaNacimiento>4 de marzo de 1678</fechaNacimiento>
  </musico>
  <musico>
    <nombre>Johann Sebastian Bach (El viejo peluca)</nombre>
    <!--<apodo>El viejo peluca</apodo>-->
    <fechaNacimiento>21 de marzo de 1685</fechaNacimiento>
  </musico>
</musicos>